#!/bin/bash --login
#SBATCH --array 4001-5000
#SBATCH --time=168:00:00
#SBATCH -J hc11b4
#SBATCH -o _log_hc11b4.%a.out
echo "test cubes11b/part.$SLURM_ARRAY_TASK_ID"
cat instance_11_HC.inccnf cubes11b/part.$SLURM_ARRAY_TASK_ID | cadical
# create CNF with "python rotsys.py -HC 11 -o instance_11_HC.inccnf"
# create cubes with "python cluster/create_cubes.py 11 cubes11b/part -p 10000"
# run with "sbatch job"
